default_agent: provisioning_agent
agents:
  onboarding_agent:
    name: onboarding_agent
    language: python
    node_version: '20'
    entrypoint: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/Agentic-Architect/agents/onboarding_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/Agentic-Architect
    aws:
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-3064316662
      execution_role_auto_create: false
      account: '905767016260'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-905767016260-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: onboarding_agent-j6Y9CIGVDj
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:runtime/onboarding_agent-j6Y9CIGVDj
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: onboarding_agent_mem-p7o543EJQT
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:memory/onboarding_agent_mem-p7o543EJQT
      memory_name: onboarding_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  provisioning_agent:
    name: provisioning_agent
    language: python
    node_version: '20'
    entrypoint: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/Agentic-Architect/agents/provisioning_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/adhavle/Documents/SDFC Industries/AWS-provisioning-mcp/Agentic-Architect
    aws:
      execution_role: arn:aws:iam::905767016260:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-bf06dcd1ee
      execution_role_auto_create: false
      account: '905767016260'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-905767016260-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: provisioning_agent-lZECd14iTW
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:runtime/provisioning_agent-lZECd14iTW
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: provisioning_agent_mem-gMv1rG8TXM
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:905767016260:memory/provisioning_agent_mem-gMv1rG8TXM
      memory_name: provisioning_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
